package main

import "database/sql"

func InserirDadosTibia(db *sql.DB) {
	CadastrarCriaturaComDrop(db, "Afflicted Strider", "Afflicted Strider Head")
	CadastrarCriaturaComDrop(db, "Afflicted Strider", "Afflicted Strider Worms")
	CadastrarCriaturaComDrop(db, "Brachiodemon", "Alloy Legs")
	CadastrarCriaturaComDrop(db, "Bulltaurm Alchemist", "Alloy Legs")
	CadastrarCriaturaComDrop(db, "Control Tower", "Alloy Legs")
	CadastrarCriaturaComDrop(db, "Metal Gargoyle", "Aloy Legs")
	CadastrarCriaturaComDrop(db, "Yirkas Blue Scales", "Alloy Legs")
	CadastrarCriaturaComDrop(db, "Quara Looter", "Amber Souvenir")
	CadastrarCriaturaComDrop(db, "Quara Raider", "Amber Souvenir")
	CadastrarCriaturaComDrop(db, "Quara Plunderer", "Amber Souvenir")
	CadastrarCriaturaComDrop(db, "Broken Shaper", "Ancient Belt Buckle")
	CadastrarCriaturaComDrop(db, "Twisted Shaper", "Ancient Belt Buckle")
	CadastrarCriaturaComDrop(db, "Ancient Spaw of Morgathla", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "Eternal Guardian", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "Ogre Brute", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "Stone Devourer", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "Stone Golem", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "The Last Lore Keeper", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "The Source Of Corruption", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "Humongous Fungus", "Angelic Axe")
	CadastrarCriaturaComDrop(db, "Mutated Tiger", "Angelic Axe")
	CadastrarCriaturaComDrop(db, "Weretiger", "Angelic Axe")
	CadastrarCriaturaComDrop(db, "Feroxa", "Angelic Axe")
	CadastrarCriaturaComDrop(db, "Many Faces", "Apron")
	CadastrarCriaturaComDrop(db, "Sharpclaw", "Badger Boots")
	CadastrarCriaturaComDrop(db, "The Baron From Below", "Badger Boots")
	CadastrarCriaturaComDrop(db, "Werebadger", "Badger Boots")
	CadastrarCriaturaComDrop(db, "Feroxa", "Badgeer Boots")
	CadastrarCriaturaComDrop(db, "Sibang", "Banana Sash")
	CadastrarCriaturaComDrop(db, "Merlkin", "Banana Sash")
	CadastrarCriaturaComDrop(db, "Wandering Pillar", "Basalt Core")
	CadastrarCriaturaComDrop(db, "Darklight Emitter", "Basalt Crumbs")
	CadastrarCriaturaComDrop(db, "Wandering Pillar", "Basalt Crumbs")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Basalt Fetish")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Basalt Fetish")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Basalt Fetish")
	CadastrarCriaturaComDrop(db, "Lost Thrower", "Basalt Fetish")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Basalt Figurine")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Basalt Figurine")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Basalt Figurine")
	CadastrarCriaturaComDrop(db, "Lost Thrower", "Basalt Figurine")
	CadastrarCriaturaComDrop(db, "Bashmu", "Bashmu Fang")
	CadastrarCriaturaComDrop(db, "Juvenile Bashmu", "Bashmu Fang")
	CadastrarCriaturaComDrop(db, "Bashmu", "Bashmu Feather")
	CadastrarCriaturaComDrop(db, "Juvenile Bashmu", "Bashmu Feather")
	CadastrarCriaturaComDrop(db, "Bashmu", "Bashmu Tongue")
	CadastrarCriaturaComDrop(db, "Juvenile Bashmu", "Bashmu Tongue")
	CadastrarCriaturaComDrop(db, "Assassin", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Cyclops", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Cyclops Drone", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Cyclops Smith", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Demon Skeleton", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Dwarf Guard", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Elf Overseer", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Foreman Kneebiter", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Frost Giant", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Frost Giantess", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Gargoyle", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Hellspaw", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Minotaur Guardian", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Mutated Bat", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Orc Rider", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Pirate Buccaneer", "Battle Shield")
	CadastrarCriaturaComDrop(db, "The Horned Fox", "Battle Shield")
	CadastrarCriaturaComDrop(db, "War Golem", "Battle Shield")
	CadastrarCriaturaComDrop(db, "General Murius", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Bruise Payne", "Black Shield")
	CadastrarCriaturaComDrop(db, "Candy Horror", "Black Shield")
	CadastrarCriaturaComDrop(db, "Gloom Maw", "Black Shield")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Black Shield")
	CadastrarCriaturaComDrop(db, "Lost Berserk", "Black Shield")
	CadastrarCriaturaComDrop(db, "Magma Crawler", "Black Shield")
	CadastrarCriaturaComDrop(db, "Mummy", "Black Shield")
	CadastrarCriaturaComDrop(db, "Mutated Bat", "Black Shield")
	CadastrarCriaturaComDrop(db, "Priestess", "Black Shield")
	CadastrarCriaturaComDrop(db, "Sandstone Scorpion", "Black Shield")
	CadastrarCriaturaComDrop(db, "Thanatursus", "Black Shield")
	CadastrarCriaturaComDrop(db, "Werehyaena Shaman", "Black Shield")
	CadastrarCriaturaComDrop(db, "Wiggler", "Black Shield")
	CadastrarCriaturaComDrop(db, "Blemished Spawn", "Blemished Spawn Abdomen")
	CadastrarCriaturaComDrop(db, "Blemished Spawn", "Blemished Spawn Head")
	CadastrarCriaturaComDrop(db, "Blemished Spawn", "Blemished Tail")
	CadastrarCriaturaComDrop(db, "Bloated Man-Maggot", "Bloated Maggot")
	CadastrarCriaturaComDrop(db, "Dworc Shadowstalker", "Blood Amulet")
	CadastrarCriaturaComDrop(db, "Norceferatu Nightweaver", "Blood Hood")
	CadastrarCriaturaComDrop(db, "Arthei", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Boreth", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Lersatio", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Nightfiend", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Vampire", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Vampire Bride", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Vampire Viscount", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Arachir The Ancient One", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Diblis The Fair", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Vicious Manbat", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Blood Hand", "Blood Tincture in a Vial")
	CadastrarCriaturaComDrop(db, "Blood Priest", "Blood Tincture in a Vial")
	CadastrarCriaturaComDrop(db, "Rotten Man-Maggot", "Blooded Worm")
	CadastrarCriaturaComDrop(db, "Orclops Bloodbreaker", "Bloodshot Giant Eye")
	CadastrarCriaturaComDrop(db, "Young Goanna", "Blue Goanna Scale")
	CadastrarCriaturaComDrop(db, "Yirkas Blue Scales", "Blue Goanna Scale")
	CadastrarCriaturaComDrop(db, "Boar Man", "Boar Man Hoof")
	CadastrarCriaturaComDrop(db, "Bog Raider", "Boggy Dreads")
	CadastrarCriaturaComDrop(db, "Weakened Shlorg", "Boggy Dreads")
	CadastrarCriaturaComDrop(db, "Corym Charlatan", "Bola")
	CadastrarCriaturaComDrop(db, "Corym Skirmisher", "Bola")
	CadastrarCriaturaComDrop(db, "Corym Vanguard", "Bola")
	CadastrarCriaturaComDrop(db, "Bonebeast", "Bone Club")
	CadastrarCriaturaComDrop(db, "Dreadbeast", "Bone Club")
	CadastrarCriaturaComDrop(db, "Goblin", "Bone Club")
	CadastrarCriaturaComDrop(db, "Goblin Assassin", "Bone Club")
	CadastrarCriaturaComDrop(db, "Goblin Leader", "Bone Club")
	CadastrarCriaturaComDrop(db, "Goblin Scavenger", "Bone Club")
	CadastrarCriaturaComDrop(db, "Muglex Clan Footman", "Bone Club")
	CadastrarCriaturaComDrop(db, "Muglex Clan Scavenger", "Bone Club")
	CadastrarCriaturaComDrop(db, "Necropharus", "Bone Club")
	CadastrarCriaturaComDrop(db, "Pirate Skeleton", "Bone Club")
	CadastrarCriaturaComDrop(db, "Salamander Trainer", "Bone Club")
	CadastrarCriaturaComDrop(db, "Troll-Trained Salamander", "Bone Club")
	CadastrarCriaturaComDrop(db, "Munster", "Bone Club")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Bone Fetish")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Bone Fetish")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Bone Fetish")
	CadastrarCriaturaComDrop(db, "Ogre Sage", "Bone Fetish")
	CadastrarCriaturaComDrop(db, "Ogre Shaman", "Bone Fetish")
	CadastrarCriaturaComDrop(db, "Orclops Bloodbreaker", "Bone Fibula")
	CadastrarCriaturaComDrop(db, "Dworc Shadowstalker", "Bone Rattle")
	CadastrarCriaturaComDrop(db, "Draken Warmaster", "Bone Shoulderplate")
	CadastrarCriaturaComDrop(db, "Orclops Bloodbreaker", "Bone Toothpick")
	CadastrarCriaturaComDrop(db, "Orclops Doomhauler", "Bone Toothpick")
	CadastrarCriaturaComDrop(db, "Orclops Ravager", "Bone Toothpick")
	CadastrarCriaturaComDrop(db, "Skeleton Elite Warrior", "Bone Toothpick")
	CadastrarCriaturaComDrop(db, "Ancient Spawn of Morgathla", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Armadile", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Darkfang", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Diamond Servant", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Diamond Servant Replica", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Hemming", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Leviathan", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Ogre Brute", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Outburst", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Ragiaz", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "The Unarmored Voidborn", "bonebreak")
	CadastrarCriaturaComDrop(db, "War Golem", "Bonebreak")
	CadastrarCriaturaComDrop(db, "Werecrocodile", "Bonebreak")
	CadastrarCriaturaComDrop(db, "Werewolf", "Bonebreak")
	CadastrarCriaturaComDrop(db, "Worker Golem", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Zavarash", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Feroxa (Mortal)", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Ghazbaran", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Bonecarving Knife")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Bonecarving Knife")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Bonecarving Knife")
	CadastrarCriaturaComDrop(db, "Bonebeast", "Bony Tail")
	CadastrarCriaturaComDrop(db, "Ribstride", "Bony Tail")
	CadastrarCriaturaComDrop(db, "Devoted Radiant Acolyte", "Book of Faith")
	CadastrarCriaturaComDrop(db, "Radiant Acolyte", "Book of Faith")
	CadastrarCriaturaComDrop(db, "Blood Hand", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Blood Priest", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Floating Savant", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Necromancer", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Necromancer Servant", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Necropharus", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Shadow Pupil", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Biting Book", "Book Page")
	CadastrarCriaturaComDrop(db, "Burning Book", "Book Page")
	CadastrarCriaturaComDrop(db, "Cursed Book", "Book Page")
	CadastrarCriaturaComDrop(db, "Energetic Book", "Book Page")
	CadastrarCriaturaComDrop(db, "Energuardian of Tales", "Book Page")
	CadastrarCriaturaComDrop(db, "Guardian of Tales", "Book Page")
	CadastrarCriaturaComDrop(db, "Icecold Book", "Book Page")
	CadastrarCriaturaComDrop(db, "knowledge Elemental", "Book Page")
	CadastrarCriaturaComDrop(db, "Headwalker", "Book with an Hourglass")
	CadastrarCriaturaComDrop(db, "Feversleep", "Bowl of Terror Sweat")
	CadastrarCriaturaComDrop(db, "Shiversleep", "Bowl of Terror Sweat")
	CadastrarCriaturaComDrop(db, "Terrorsleep", "Bowl of Terror Sweat")
	CadastrarCriaturaComDrop(db, "Candy Horror", "Brigadeiro")
	CadastrarCriaturaComDrop(db, "Sugar Daddy", "Brigadeiro")
	CadastrarCriaturaComDrop(db, "Brinebrute Inferniarch", "Brinebrute Claw")
	CadastrarCriaturaComDrop(db, "Malvaroth", "Brinebrute Claw")
	CadastrarCriaturaComDrop(db, "Afflicted Strider", "Broadsword")
	CadastrarCriaturaComDrop(db, "Dragon", "Broadsword")
	CadastrarCriaturaComDrop(db, "Orc Leader", "Broadsword")
	CadastrarCriaturaComDrop(db, "Renegade Orc", "Broadsword")
	CadastrarCriaturaComDrop(db, "Draken Elite", "Broken Draken Mail")
	CadastrarCriaturaComDrop(db, "Paiz The Pauperizer", "Broken Draken Mail")
	CadastrarCriaturaComDrop(db, "Undead Elite Gladiator", "Broken Gladiator Shield")
	CadastrarCriaturaComDrop(db, "Undead Gladiator", "Broken Gladiator Shield")
	CadastrarCriaturaComDrop(db, "Lizard Legionnaire", "Broken Halberd")
	CadastrarCriaturaComDrop(db, "Atab", "Broken Mitmah Necklace")
	CadastrarCriaturaComDrop(db, "Mitmah Scout", "Broken Mitmah Necklace")
	CadastrarCriaturaComDrop(db, "Mitmah Vanguard", "Broken Mitmah Necklace")
	CadastrarCriaturaComDrop(db, "Draken Elite", "Broken Slicer")
	CadastrarCriaturaComDrop(db, "Paiz The Pauperizer", "Broken Slicer")
	CadastrarCriaturaComDrop(db, "Lost Thrower", "Broken Throwing Axe")
	CadastrarCriaturaComDrop(db, "Broodrider Inferniach", "Broodrider Saddle")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Buckle")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Buckle")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Buckle")
	CadastrarCriaturaComDrop(db, "Lost Thrower", "Buckle")
	CadastrarCriaturaComDrop(db, "Spiky Carnivor", "Buckle")
	CadastrarCriaturaComDrop(db, "Bulltaur Brute", "Bulltaur Armor Scrap")
	CadastrarCriaturaComDrop(db, "Bulltaur Brute", "Bulltaur Hoof")
	CadastrarCriaturaComDrop(db, "Bulltaur Alchemist", "Bulltaur Horn")
	CadastrarCriaturaComDrop(db, "Bulltaur Brute", "Bulltaur Horn")
	CadastrarCriaturaComDrop(db, "Bulltaur Forgepriest", "Bulltaur Horn")
	CadastrarCriaturaComDrop(db, "Blightwalker", "Bundle of Cursed Straw")
	CadastrarCriaturaComDrop(db, "Capricious Phantom", "Capricious Heart")
	CadastrarCriaturaComDrop(db, "Capricious Phantom", "Capricious Robe")
	CadastrarCriaturaComDrop(db, "Carnisylvan Sapling", "Carnisylvan Bark")
	CadastrarCriaturaComDrop(db, "Dark Carnisylvan", "Carnisylvan Bark")
	CadastrarCriaturaComDrop(db, "Hulking Carnisylvan", "Carnisylvan Bark")
	CadastrarCriaturaComDrop(db, "Poisonous Carnisylvan", "Carnisylvan Bark")
	CadastrarCriaturaComDrop(db, "Dark Carnisylvan", "Carnisylvan Finger")
	CadastrarCriaturaComDrop(db, "Hulking Carnisylvan", "Carnisylvan Finger")
	CadastrarCriaturaComDrop(db, "Poisonous Carnilsylvan", "Carnisylvan Finger")
	CadastrarCriaturaComDrop(db, "Carnivostrich", "Carnivostrich Feather")
	CadastrarCriaturaComDrop(db, "Dark Torturer", "Cat's Paw")
	CadastrarCriaturaComDrop(db, "Hemming", "Cat's Paw")
	CadastrarCriaturaComDrop(db, "The Scourge of Oblivion", "Cat's Paw")
	CadastrarCriaturaComDrop(db, "Mr. Punish", "Cat's Paw")
	CadastrarCriaturaComDrop(db, "Cave Chimera", "Cave Chimera Head")
	CadastrarCriaturaComDrop(db, "Cave Chimera", "Cave Chimera Leg")
	CadastrarCriaturaComDrop(db, "Cave Devourer", "Cave Devourer Eyes")
	CadastrarCriaturaComDrop(db, "Cave Devourer", "Cave Devourer Legs")
	CadastrarCriaturaComDrop(db, "Cave Devourer", "Cave Devourer Maw")
	CadastrarCriaturaComDrop(db, "Centipede", "Centipede Leg")
	CadastrarCriaturaComDrop(db, "Gloom Maw", "Chain Leash")
	//continua em Chaos Mace
}