package main

import "database/sql"

func InserirDadosTibia(db *sql.DB) {
	CadastrarCriaturaComDrop(db, "Afflicted Strider", "Afflicted Strider Head")
	CadastrarCriaturaComDrop(db, "Afflicted Strider", "Afflicted Strider Worms")
	CadastrarCriaturaComDrop(db, "Brachiodemon", "Alloy Legs")
	CadastrarCriaturaComDrop(db, "Bulltaurm Alchemist", "Alloy Legs")
	CadastrarCriaturaComDrop(db, "Control Tower", "Alloy Legs")
	CadastrarCriaturaComDrop(db, "Metal Gargoyle", "Aloy Legs")
	CadastrarCriaturaComDrop(db, "Yirkas Blue Scales", "Alloy Legs")
	CadastrarCriaturaComDrop(db, "Quara Looter", "Amber Souvenir")
	CadastrarCriaturaComDrop(db, "Quara Raider", "Amber Souvenir")
	CadastrarCriaturaComDrop(db, "Quara Plunderer", "Amber Souvenir")
	CadastrarCriaturaComDrop(db, "Broken Shaper", "Ancient Belt Buckle")
	CadastrarCriaturaComDrop(db, "Twisted Shaper", "Ancient Belt Buckle")
	CadastrarCriaturaComDrop(db, "Ancient Spaw of Morgathla", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "Eternal Guardian", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "Ogre Brute", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "Stone Devourer", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "Stone Golem", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "The Last Lore Keeper", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "The Source Of Corruption", "Ancient Stone")
	CadastrarCriaturaComDrop(db, "Humongous Fungus", "Angelic Axe")
	CadastrarCriaturaComDrop(db, "Mutated Tiger", "Angelic Axe")
	CadastrarCriaturaComDrop(db, "Weretiger", "Angelic Axe")
	CadastrarCriaturaComDrop(db, "Feroxa", "Angelic Axe")
	CadastrarCriaturaComDrop(db, "Many Faces", "Apron")
	CadastrarCriaturaComDrop(db, "Sharpclaw", "Badger Boots")
	CadastrarCriaturaComDrop(db, "The Baron From Below", "Badger Boots")
	CadastrarCriaturaComDrop(db, "Werebadger", "Badger Boots")
	CadastrarCriaturaComDrop(db, "Feroxa", "Badgeer Boots")
	CadastrarCriaturaComDrop(db, "Sibang", "Banana Sash")
	CadastrarCriaturaComDrop(db, "Merlkin", "Banana Sash")
	CadastrarCriaturaComDrop(db, "Wandering Pillar", "Basalt Core")
	CadastrarCriaturaComDrop(db, "Darklight Emitter", "Basalt Crumbs")
	CadastrarCriaturaComDrop(db, "Wandering Pillar", "Basalt Crumbs")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Basalt Fetish")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Basalt Fetish")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Basalt Fetish")
	CadastrarCriaturaComDrop(db, "Lost Thrower", "Basalt Fetish")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Basalt Figurine")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Basalt Figurine")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Basalt Figurine")
	CadastrarCriaturaComDrop(db, "Lost Thrower", "Basalt Figurine")
	CadastrarCriaturaComDrop(db, "Bashmu", "Bashmu Fang")
	CadastrarCriaturaComDrop(db, "Juvenile Bashmu", "Bashmu Fang")
	CadastrarCriaturaComDrop(db, "Bashmu", "Bashmu Feather")
	CadastrarCriaturaComDrop(db, "Juvenile Bashmu", "Bashmu Feather")
	CadastrarCriaturaComDrop(db, "Bashmu", "Bashmu Tongue")
	CadastrarCriaturaComDrop(db, "Juvenile Bashmu", "Bashmu Tongue")
	CadastrarCriaturaComDrop(db, "Assassin", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Cyclops", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Cyclops Drone", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Cyclops Smith", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Demon Skeleton", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Dwarf Guard", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Elf Overseer", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Foreman Kneebiter", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Frost Giant", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Frost Giantess", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Gargoyle", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Hellspaw", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Minotaur Guardian", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Mutated Bat", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Orc Rider", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Pirate Buccaneer", "Battle Shield")
	CadastrarCriaturaComDrop(db, "The Horned Fox", "Battle Shield")
	CadastrarCriaturaComDrop(db, "War Golem", "Battle Shield")
	CadastrarCriaturaComDrop(db, "General Murius", "Battle Shield")
	CadastrarCriaturaComDrop(db, "Bruise Payne", "Black Shield")
	CadastrarCriaturaComDrop(db, "Candy Horror", "Black Shield")
	CadastrarCriaturaComDrop(db, "Gloom Maw", "Black Shield")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Black Shield")
	CadastrarCriaturaComDrop(db, "Lost Berserk", "Black Shield")
	CadastrarCriaturaComDrop(db, "Magma Crawler", "Black Shield")
	CadastrarCriaturaComDrop(db, "Mummy", "Black Shield")
	CadastrarCriaturaComDrop(db, "Mutated Bat", "Black Shield")
	CadastrarCriaturaComDrop(db, "Priestess", "Black Shield")
	CadastrarCriaturaComDrop(db, "Sandstone Scorpion", "Black Shield")
	CadastrarCriaturaComDrop(db, "Thanatursus", "Black Shield")
	CadastrarCriaturaComDrop(db, "Werehyaena Shaman", "Black Shield")
	CadastrarCriaturaComDrop(db, "Wiggler", "Black Shield")
	CadastrarCriaturaComDrop(db, "Blemished Spawn", "Blemished Spawn Abdomen")
	CadastrarCriaturaComDrop(db, "Blemished Spawn", "Blemished Spawn Head")
	CadastrarCriaturaComDrop(db, "Blemished Spawn", "Blemished Tail")
	CadastrarCriaturaComDrop(db, "Bloated Man-Maggot", "Bloated Maggot")
	CadastrarCriaturaComDrop(db, "Dworc Shadowstalker", "Blood Amulet")
	CadastrarCriaturaComDrop(db, "Norceferatu Nightweaver", "Blood Hood")
	CadastrarCriaturaComDrop(db, "Arthei", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Boreth", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Lersatio", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Nightfiend", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Vampire", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Vampire Bride", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Vampire Viscount", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Arachir The Ancient One", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Diblis The Fair", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Vicious Manbat", "Blood Preservation")
	CadastrarCriaturaComDrop(db, "Blood Hand", "Blood Tincture in a Vial")
	CadastrarCriaturaComDrop(db, "Blood Priest", "Blood Tincture in a Vial")
	CadastrarCriaturaComDrop(db, "Rotten Man-Maggot", "Blooded Worm")
	CadastrarCriaturaComDrop(db, "Orclops Bloodbreaker", "Bloodshot Giant Eye")
	CadastrarCriaturaComDrop(db, "Young Goanna", "Blue Goanna Scale")
	CadastrarCriaturaComDrop(db, "Yirkas Blue Scales", "Blue Goanna Scale")
	CadastrarCriaturaComDrop(db, "Boar Man", "Boar Man Hoof")
	CadastrarCriaturaComDrop(db, "Bog Raider", "Boggy Dreads")
	CadastrarCriaturaComDrop(db, "Weakened Shlorg", "Boggy Dreads")
	CadastrarCriaturaComDrop(db, "Corym Charlatan", "Bola")
	CadastrarCriaturaComDrop(db, "Corym Skirmisher", "Bola")
	CadastrarCriaturaComDrop(db, "Corym Vanguard", "Bola")
	CadastrarCriaturaComDrop(db, "Bonebeast", "Bone Club")
	CadastrarCriaturaComDrop(db, "Dreadbeast", "Bone Club")
	CadastrarCriaturaComDrop(db, "Goblin", "Bone Club")
	CadastrarCriaturaComDrop(db, "Goblin Assassin", "Bone Club")
	CadastrarCriaturaComDrop(db, "Goblin Leader", "Bone Club")
	CadastrarCriaturaComDrop(db, "Goblin Scavenger", "Bone Club")
	CadastrarCriaturaComDrop(db, "Muglex Clan Footman", "Bone Club")
	CadastrarCriaturaComDrop(db, "Muglex Clan Scavenger", "Bone Club")
	CadastrarCriaturaComDrop(db, "Necropharus", "Bone Club")
	CadastrarCriaturaComDrop(db, "Pirate Skeleton", "Bone Club")
	CadastrarCriaturaComDrop(db, "Salamander Trainer", "Bone Club")
	CadastrarCriaturaComDrop(db, "Troll-Trained Salamander", "Bone Club")
	CadastrarCriaturaComDrop(db, "Munster", "Bone Club")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Bone Fetish")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Bone Fetish")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Bone Fetish")
	CadastrarCriaturaComDrop(db, "Ogre Sage", "Bone Fetish")
	CadastrarCriaturaComDrop(db, "Ogre Shaman", "Bone Fetish")
	CadastrarCriaturaComDrop(db, "Orclops Bloodbreaker", "Bone Fibula")
	CadastrarCriaturaComDrop(db, "Dworc Shadowstalker", "Bone Rattle")
	CadastrarCriaturaComDrop(db, "Draken Warmaster", "Bone Shoulderplate")
	CadastrarCriaturaComDrop(db, "Orclops Bloodbreaker", "Bone Toothpick")
	CadastrarCriaturaComDrop(db, "Orclops Doomhauler", "Bone Toothpick")
	CadastrarCriaturaComDrop(db, "Orclops Ravager", "Bone Toothpick")
	CadastrarCriaturaComDrop(db, "Skeleton Elite Warrior", "Bone Toothpick")
	CadastrarCriaturaComDrop(db, "Ancient Spawn of Morgathla", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Armadile", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Darkfang", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Diamond Servant", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Diamond Servant Replica", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Hemming", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Leviathan", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Ogre Brute", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Outburst", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Ragiaz", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "The Unarmored Voidborn", "bonebreak")
	CadastrarCriaturaComDrop(db, "War Golem", "Bonebreak")
	CadastrarCriaturaComDrop(db, "Werecrocodile", "Bonebreak")
	CadastrarCriaturaComDrop(db, "Werewolf", "Bonebreak")
	CadastrarCriaturaComDrop(db, "Worker Golem", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Zavarash", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Feroxa (Mortal)", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Ghazbaran", "Bonebreaker")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Bonecarving Knife")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Bonecarving Knife")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Bonecarving Knife")
	CadastrarCriaturaComDrop(db, "Bonebeast", "Bony Tail")
	CadastrarCriaturaComDrop(db, "Ribstride", "Bony Tail")
	CadastrarCriaturaComDrop(db, "Devoted Radiant Acolyte", "Book of Faith")
	CadastrarCriaturaComDrop(db, "Radiant Acolyte", "Book of Faith")
	CadastrarCriaturaComDrop(db, "Blood Hand", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Blood Priest", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Floating Savant", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Necromancer", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Necromancer Servant", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Necropharus", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Shadow Pupil", "Book of Necromantic Rituals")
	CadastrarCriaturaComDrop(db, "Biting Book", "Book Page")
	CadastrarCriaturaComDrop(db, "Burning Book", "Book Page")
	CadastrarCriaturaComDrop(db, "Cursed Book", "Book Page")
	CadastrarCriaturaComDrop(db, "Energetic Book", "Book Page")
	CadastrarCriaturaComDrop(db, "Energuardian of Tales", "Book Page")
	CadastrarCriaturaComDrop(db, "Guardian of Tales", "Book Page")
	CadastrarCriaturaComDrop(db, "Icecold Book", "Book Page")
	CadastrarCriaturaComDrop(db, "knowledge Elemental", "Book Page")
	CadastrarCriaturaComDrop(db, "Headwalker", "Book with an Hourglass")
	CadastrarCriaturaComDrop(db, "Feversleep", "Bowl of Terror Sweat")
	CadastrarCriaturaComDrop(db, "Shiversleep", "Bowl of Terror Sweat")
	CadastrarCriaturaComDrop(db, "Terrorsleep", "Bowl of Terror Sweat")
	CadastrarCriaturaComDrop(db, "Candy Horror", "Brigadeiro")
	CadastrarCriaturaComDrop(db, "Sugar Daddy", "Brigadeiro")
	CadastrarCriaturaComDrop(db, "Brinebrute Inferniarch", "Brinebrute Claw")
	CadastrarCriaturaComDrop(db, "Malvaroth", "Brinebrute Claw")
	CadastrarCriaturaComDrop(db, "Afflicted Strider", "Broadsword")
	CadastrarCriaturaComDrop(db, "Dragon", "Broadsword")
	CadastrarCriaturaComDrop(db, "Orc Leader", "Broadsword")
	CadastrarCriaturaComDrop(db, "Renegade Orc", "Broadsword")
	CadastrarCriaturaComDrop(db, "Draken Elite", "Broken Draken Mail")
	CadastrarCriaturaComDrop(db, "Paiz The Pauperizer", "Broken Draken Mail")
	CadastrarCriaturaComDrop(db, "Undead Elite Gladiator", "Broken Gladiator Shield")
	CadastrarCriaturaComDrop(db, "Undead Gladiator", "Broken Gladiator Shield")
	CadastrarCriaturaComDrop(db, "Lizard Legionnaire", "Broken Halberd")
	CadastrarCriaturaComDrop(db, "Atab", "Broken Mitmah Necklace")
	CadastrarCriaturaComDrop(db, "Mitmah Scout", "Broken Mitmah Necklace")
	CadastrarCriaturaComDrop(db, "Mitmah Vanguard", "Broken Mitmah Necklace")
	CadastrarCriaturaComDrop(db, "Draken Elite", "Broken Slicer")
	CadastrarCriaturaComDrop(db, "Paiz The Pauperizer", "Broken Slicer")
	CadastrarCriaturaComDrop(db, "Lost Thrower", "Broken Throwing Axe")
	CadastrarCriaturaComDrop(db, "Broodrider Inferniach", "Broodrider Saddle")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Buckle")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Buckle")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Buckle")
	CadastrarCriaturaComDrop(db, "Lost Thrower", "Buckle")
	CadastrarCriaturaComDrop(db, "Spiky Carnivor", "Buckle")
	CadastrarCriaturaComDrop(db, "Bulltaur Brute", "Bulltaur Armor Scrap")
	CadastrarCriaturaComDrop(db, "Bulltaur Brute", "Bulltaur Hoof")
	CadastrarCriaturaComDrop(db, "Bulltaur Alchemist", "Bulltaur Horn")
	CadastrarCriaturaComDrop(db, "Bulltaur Brute", "Bulltaur Horn")
	CadastrarCriaturaComDrop(db, "Bulltaur Forgepriest", "Bulltaur Horn")
	CadastrarCriaturaComDrop(db, "Blightwalker", "Bundle of Cursed Straw")
	CadastrarCriaturaComDrop(db, "Capricious Phantom", "Capricious Heart")
	CadastrarCriaturaComDrop(db, "Capricious Phantom", "Capricious Robe")
	CadastrarCriaturaComDrop(db, "Carnisylvan Sapling", "Carnisylvan Bark")
	CadastrarCriaturaComDrop(db, "Dark Carnisylvan", "Carnisylvan Bark")
	CadastrarCriaturaComDrop(db, "Hulking Carnisylvan", "Carnisylvan Bark")
	CadastrarCriaturaComDrop(db, "Poisonous Carnisylvan", "Carnisylvan Bark")
	CadastrarCriaturaComDrop(db, "Dark Carnisylvan", "Carnisylvan Finger")
	CadastrarCriaturaComDrop(db, "Hulking Carnisylvan", "Carnisylvan Finger")
	CadastrarCriaturaComDrop(db, "Poisonous Carnilsylvan", "Carnisylvan Finger")
	CadastrarCriaturaComDrop(db, "Carnivostrich", "Carnivostrich Feather")
	CadastrarCriaturaComDrop(db, "Dark Torturer", "Cat's Paw")
	CadastrarCriaturaComDrop(db, "Hemming", "Cat's Paw")
	CadastrarCriaturaComDrop(db, "The Scourge of Oblivion", "Cat's Paw")
	CadastrarCriaturaComDrop(db, "Mr. Punish", "Cat's Paw")
	CadastrarCriaturaComDrop(db, "Cave Chimera", "Cave Chimera Head")
	CadastrarCriaturaComDrop(db, "Cave Chimera", "Cave Chimera Leg")
	CadastrarCriaturaComDrop(db, "Cave Devourer", "Cave Devourer Eyes")
	CadastrarCriaturaComDrop(db, "Cave Devourer", "Cave Devourer Legs")
	CadastrarCriaturaComDrop(db, "Cave Devourer", "Cave Devourer Maw")
	CadastrarCriaturaComDrop(db, "Centipede", "Centipede Leg")
	CadastrarCriaturaComDrop(db, "Gloom Maw", "Chain Leash")
	CadastrarCriaturaComDrop(db, "Alptramun", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Anomaly", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Bretzecutioner", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Destroyer", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Ferumbras Mortal Shell", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Gorzindel", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Infernal Phantom", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Izcandar the Banished", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Juvenile Bashmu", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Lost Berserker", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Malofur Mangrinder", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Moohtant", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Nightstalker", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Norcferatu Heartless", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Outburst", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Plagueroot", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Rupture", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Shulgrax", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "The Nightmare Beast", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "The Scourge of Oblivion", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "The Shatterer", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Utua Stone Sting", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Ferumbras", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Sir Valorcrest", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "The Pale Count", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "The Percht Queen", "Chaos Mace")
	CadastrarCriaturaComDrop(db, "Chasm Spawn", "Chasm Spawn Abdomen")
	CadastrarCriaturaComDrop(db, "Chasm Spawn", "Chasm Spawn Head")
	CadastrarCriaturaComDrop(db, "Chasm Spawn", "Chasm Spawn Tail")
	CadastrarCriaturaComDrop(db, "Corym Charlatan", "Cheese Cutter")
	CadastrarCriaturaComDrop(db, "Corym Skirmisher", "Cheese Cutter")
	CadastrarCriaturaComDrop(db, "Corym Vanguard", "Cheese Cutter")
	CadastrarCriaturaComDrop(db, "Cobra Scout", "Cheese Figurine")
	CadastrarCriaturaComDrop(db, "Corym Skirmisher", "Cheese Figurine")
	CadastrarCriaturaComDrop(db, "Corym Vanguard", "Cheese Figurine")
	CadastrarCriaturaComDrop(db, "Corym Charlatan", "Cheese Figurine")
	CadastrarCriaturaComDrop(db, "Devoted Radiant Acolyte", "Cloud Familiar")
	CadastrarCriaturaComDrop(db, "Devoted Radiant Inquisitor", "Could Familiar")
	CadastrarCriaturaComDrop(db, "Devoted Radiant Paragon", "Cloud Familiar")
	CadastrarCriaturaComDrop(db, "Devoted Radiant Templar", "Cloud Familiar")
	CadastrarCriaturaComDrop(db, "Devoted Radiant Warden", "Cloud Familiar")
	CadastrarCriaturaComDrop(db, "Devoted Radiant Zealot", "Cloud Familiar")
	CadastrarCriaturaComDrop(db, "Creepy Crawler", "Cluster of Crystallized Death")
	CadastrarCriaturaComDrop(db, "Crypt Construct", "Cluster of Crystallized Death")
	CadastrarCriaturaComDrop(db, "Crypt Fiend", "Cluster of Crystallized Death")
	CadastrarCriaturaComDrop(db, "Cobra Assassin", "Cobra Crest")
	CadastrarCriaturaComDrop(db, "Cobra Scout", "Cobra Crest")
	CadastrarCriaturaComDrop(db, "Cobra Vizier", "Cobra Crest")
	CadastrarCriaturaComDrop(db, "Guardian Captain Quaid", "Cobra Crest")
	CadastrarCriaturaComDrop(db, "Terror Bird", "Colourful Feather")
	CadastrarCriaturaComDrop(db, "Iks Yapunac", "Colourful Feather")
	CadastrarCriaturaComDrop(db, "Nymph", "Colourful Snail Shell")
	CadastrarCriaturaComDrop(db, "Pixie", "Colourful Snail Shell")
	CadastrarCriaturaComDrop(db, "Swan Maiden", "Colourful Snail Shell")
	CadastrarCriaturaComDrop(db, "Ancient Lion Knight", "Combat Knife")
	CadastrarCriaturaComDrop(db, "Assassin", "Combat Knife")
	CadastrarCriaturaComDrop(db, "Enraged Soul", "Combat Knife")
	CadastrarCriaturaComDrop(db, "Foam Stalker", "Combat Knife")
	CadastrarCriaturaComDrop(db, "Ghost", "Combat Knife")
	CadastrarCriaturaComDrop(db, "Goggle Cake", "Combat Knife")
	CadastrarCriaturaComDrop(db, "Smuggler", "Combat Knife")
	CadastrarCriaturaComDrop(db, "Tarnished Spirit", "Combat Knife")
	CadastrarCriaturaComDrop(db, "Werehyaena", "Combat Knife")
	CadastrarCriaturaComDrop(db, "Crawler", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Chopper", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Fleshslicer", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Hive Overseer", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Insectoid Worker", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Kollos", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Maw", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Mindmasher", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Shadowstalker", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Spidris", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Spidris Elite", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Spitter", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Swarmer", "Compound Eye")
	CadastrarCriaturaComDrop(db, "The Manhunter", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Waspoid", "Compound Eye")
	CadastrarCriaturaComDrop(db, "Crusader", "Cookbook (Book World)")
	CadastrarCriaturaComDrop(db, "Foam Stalker", "Coral Branch")
	CadastrarCriaturaComDrop(db, "Minotaur Amazon", "Cowbell")
	CadastrarCriaturaComDrop(db, "Minotaur Cult Follower", "Cowbell")
	CadastrarCriaturaComDrop(db, "Minotaur Cult Prophet", "Cowbell")
	CadastrarCriaturaComDrop(db, "Minotaur Cult Zealot", "Cowbell")
	CadastrarCriaturaComDrop(db, "Crape Man", "Crab Man Claws")
	CadastrarCriaturaComDrop(db, "Broken Shaper", "Cracked Alabaster Vase")
	CadastrarCriaturaComDrop(db, "Shaper Matriarch", "Cracked Alabaster Vase")
	CadastrarCriaturaComDrop(db, "Twisted Shaper", "Cracked Alabaster Vase")
	CadastrarCriaturaComDrop(db, "Branchy Crawler", "Crawler's Essence")
	CadastrarCriaturaComDrop(db, "Cloak Of Terror", "Crown (Cloak Of Terror)")
	CadastrarCriaturaComDrop(db, "Instable Breach Brood", "Crystal Bone")
	CadastrarCriaturaComDrop(db, "Abyssador", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Branchy Crawler", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Cave Chimera", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Cliff Strider", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Crazed Summer Rearguard", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Cyclursus", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Deathstrike", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Freakish Lost Soul", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Gnomevil", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Gorerilla", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Haunted Hunter", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Mould Phantom", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Naga Archer", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Orewalker", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Quara Looter", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Sulphur Spouter", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Vok the Freakish", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Zamulosh", "Crystal Crossbow")
	CadastrarCriaturaComDrop(db, "Animated Feather", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Boar Man", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Brachiodemon", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Eradicator", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Eyeless Devourer", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Ice Horror", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Icecold Book", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Infernal Phantom", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Ironblight", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Juvenile Bashmu", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Melting Frozen Horror", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Roaming Dread", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Squid Warden", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Stone Devourer", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Streaked Devourer", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Tamru the Black", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "The Baron from Below", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Tunnel Tyrant", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Utua Stone Sting", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Vashresamun", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Walker", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Zamulosh", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Zushuka (Mortal)", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Yakchal", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Sight of Surrender", "Crystal Mace")
	CadastrarCriaturaComDrop(db, "Afflicted Strider", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Barbarian Skullhunter", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Boar Man", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Crystal Spider", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Elf Overseer", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Energy Elemental", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Enraged Crystal Golem", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "High Voltage Elemental", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Icel Golem", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Ice Witch", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Knowledge Elemental", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Madareth", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Melting Frozen Horror", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Menacing Carnivor", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Nighthunter", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Pirat Cutthroat", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Rotspit", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Shardhead", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Spitter", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Squid Warden", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Werelion", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Werelioness", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Hirintror", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Zushuka (Mortal)", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Yakchal", "Crystal Sword")
	CadastrarCriaturaComDrop(db, "Animated Feather", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Armadile", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Blight Mariner", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Crystal Wolf", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Darklight Source", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Diamond Servant", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Diamond Servant Replica", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Eradicator", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Haunted Hunter", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Icecold Book", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Ice Overlord", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Mazzinor", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Melting Frozen Horror", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Michael the Stalwart", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Orewalker", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Prince Drazzak", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Realityquake", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Ravenous Hunger", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Roaming Dread", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Sea Serpent", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Squid Warden", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "The Count Of The Core", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Tunnel Tyrant", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Turbulent Elemental", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Ghazbaran", "Crystalline Armor")
	CadastrarCriaturaComDrop(db, "Armadile", "Crystalline Spikes")
	CadastrarCriaturaComDrop(db, "Crystalcrusher", "Crystalline Spikes")
	CadastrarCriaturaComDrop(db, "Enraged Crystal Golem", "Crystalline Spikes")
	CadastrarCriaturaComDrop(db, "Ironblight", "Crystalline Spikes")
	CadastrarCriaturaComDrop(db, "Stone Devourer", "Crystalline Spikes")
	CadastrarCriaturaComDrop(db, "Abyssador", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Anomaly", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Brachiodemon", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Branchy Crawler", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Cliff Strider", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Deathstrike", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Gorzindel", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Gnomevil", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Harpy", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Melting Frozen Horror", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Outburst", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "The Source Of Corruption", "Crystalline Sword")
	CadastrarCriaturaComDrop(db, "Creepy Crawler", "Crystallized Death")
	CadastrarCriaturaComDrop(db, "Crypt Construct", "Crystallized Death")
	CadastrarCriaturaComDrop(db, "Crypt Fiend", "Crystallized Death")
	CadastrarCriaturaComDrop(db, "Crypt Mage", "Crystallized Death")
	CadastrarCriaturaComDrop(db, "Cyclursus", "Crystallized Death")
	CadastrarCriaturaComDrop(db, "Haunted Hunter", "Crystallized Death")
	CadastrarCriaturaComDrop(db, "Roaming Dread", "Crystallized Death")
	CadastrarCriaturaComDrop(db, "Walking Dread", "Crystallized Death")
	CadastrarCriaturaComDrop(db, "Adlerauge", "Cuirass Plate")
	CadastrarCriaturaComDrop(db, "Michael the Stalwart", "Cuirass Plate")
	CadastrarCriaturaComDrop(db, "Raubritter Marksman", "Cuirass Plate")
	CadastrarCriaturaComDrop(db, "Raubritter Skirmisher", "Cuirass Plate")
	CadastrarCriaturaComDrop(db, "Anomaly", "Curious Matter")
	CadastrarCriaturaComDrop(db, "Breach Brood", "Curious Matter")
	CadastrarCriaturaComDrop(db, "Burster", "Curious Matter")
	CadastrarCriaturaComDrop(db, "Gorzindel", "Curious Matter")
	CadastrarCriaturaComDrop(db, "The Souldespoiler", "Curious Matter")
	CadastrarCriaturaComDrop(db, "Lizard Chosen", "Cursed Shoulder Spikes")
	CadastrarCriaturaComDrop(db, "The Voice of Ruin", "Cursed Shoulder Spikes")
	CadastrarCriaturaComDrop(db, "Falcon Knight", "Damaged Armor Plates")
	CadastrarCriaturaComDrop(db, "Falcon Paladin", "Damaged Armor Plates")
	CadastrarCriaturaComDrop(db, "Grand Chaplain Gaunder", "Damaged Armor Plates")
	CadastrarCriaturaComDrop(db, "Grand Commander Soeren", "Damaged Armor Plates")
	CadastrarCriaturaComDrop(db, "Dawnfly", "Damselfly Eye")
	CadastrarCriaturaComDrop(db, "Emerald Damselfly", "Damselfly Eye")
	CadastrarCriaturaComDrop(db, "Arctic Faun", "Dandelion Seeds")
	CadastrarCriaturaComDrop(db, "Faun", "Dandelion Seeds")
	CadastrarCriaturaComDrop(db, "Nymph", "Dandelion Seeds")
	CadastrarCriaturaComDrop(db, "Pixie", "Dandelion Seeds")
	CadastrarCriaturaComDrop(db, "Reality Reaver", "Dangerous Proto Matter")
	CadastrarCriaturaComDrop(db, "Darklight Construct", "Darl Obsidian Splinter")
	CadastrarCriaturaComDrop(db, "Darklight Source", "Darlk Obsidian Splinter")
	CadastrarCriaturaComDrop(db, "Priestess", "Dark Rosary")
	CadastrarCriaturaComDrop(db, "Dark Monk", "Dark Rosary")
	CadastrarCriaturaComDrop(db, "Ancient Lion Knight", "Dark Shield")
	CadastrarCriaturaComDrop(db, "Grim Reaper", "Dark Shield")
	CadastrarCriaturaComDrop(db, "Michael the Stalwart", "Dark Shield")
	CadastrarCriaturaComDrop(db, "Pirate Corsair", "Dark Shield")
	CadastrarCriaturaComDrop(db, "Silencer", "Dark Shield")
	CadastrarCriaturaComDrop(db, "Thanatursus", "Dark Shield")
	CadastrarCriaturaComDrop(db, "Werelion", "Dark Shield")
	CadastrarCriaturaComDrop(db, "The Handmaiden", "Dark Shield")
	CadastrarCriaturaComDrop(db, "Haunted Dragon", "Dark Shield")
	CadastrarCriaturaComDrop(db, "Walking Pillar", "Darklight Basalt Chunk")
	CadastrarCriaturaComDrop(db, "Choking Fear", "Dead Weight")
	CadastrarCriaturaComDrop(db, "Cyclursus", "Deadly Fangs")
	CadastrarCriaturaComDrop(db, "Haunted Hunter", "Deadly Fangs")
	CadastrarCriaturaComDrop(db, "Oozing Carcass", "Decayed Finger Bone")
	CadastrarCriaturaComDrop(db, "Sopping Carcass", "Decayed Finger Bone")
	CadastrarCriaturaComDrop(db, "Deepling Guard", "Deepling Breaktime Snack")
	CadastrarCriaturaComDrop(db, "Deepling Tyrant", "Deepling Breaktime Snack")
	CadastrarCriaturaComDrop(db, "Deepling Guard", "Deepling Claw")
	CadastrarCriaturaComDrop(db, "Deepling Tyrant", "Deepling Claw")
	CadastrarCriaturaComDrop(db, "Deepling Guard", "Deepling Guard Belt Buckle")
	CadastrarCriaturaComDrop(db, "Deepling Tyrant", "Deepling Guard Belt Buckle")
	CadastrarCriaturaComDrop(db, "Deathling Scout", "Deepling Ridge")
	CadastrarCriaturaComDrop(db, "Deatlhing Spellsinger", "Deepling Ridge")
	CadastrarCriaturaComDrop(db, "Deepling Warrior", "Deepling Ridge")
	CadastrarCriaturaComDrop(db, "Deepling Elite", "Deepling Ridge")
	CadastrarCriaturaComDrop(db, "Deepworm", "Deepworm Jaws")
	CadastrarCriaturaComDrop(db, "Deepworm", "Deepworm Spike Roots")
	CadastrarCriaturaComDrop(db, "Deepworm", "Deepworm Spikes")
	CadastrarCriaturaComDrop(db, "Rootthing Amber Shaper", "Demon Root")
	CadastrarCriaturaComDrop(db, "Rootthing Bug Tracker", "Demon Root")
	CadastrarCriaturaComDrop(db, "Rootthing Nutshell", "Demon Root")
	CadastrarCriaturaComDrop(db, "Brinebrute Inferniach", "Demonic Matter")
	CadastrarCriaturaComDrop(db, "Broodrider Inferniarch", "Demonic Matter")
	CadastrarCriaturaComDrop(db, "Gorger Inferniarch", "Demonic Matter")
	CadastrarCriaturaComDrop(db, "Gralvalon", "Demonic Matter")
	CadastrarCriaturaComDrop(db, "Hellhunter Inferniach", "Demonic Matter")
	CadastrarCriaturaComDrop(db, "Malvaroth", "Demonic Matter")
	CadastrarCriaturaComDrop(db, "Sineater Inferniach", "Demonic Matter")
	CadastrarCriaturaComDrop(db, "Spellreaper Inferniach", "Demonic Matter")
	CadastrarCriaturaComDrop(db, "Twisterror", "Demonic Matter")
	CadastrarCriaturaComDrop(db, "Animated Feather", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Annihilon", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Blemished Spawn", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Cursed Book", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Enfeebled Silencer", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Girtablilu Warrior", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Gore Horn", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Hulking Carnisylvan", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Icecold Book", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Ice Witch", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Juvenile Bashmu", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Massive Earth Elemental", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Nightmare Scion", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Ogre Ruffian", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Poisonous Carnisylvan", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Silencer", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Squid Warden", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Swan Maiden", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Varnished Diremaw", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Zavarash", "Diamond Sceptre")
	CadastrarCriaturaComDrop(db, "Diremaw", "Diremaw Brainpan")
	CadastrarCriaturaComDrop(db, "Diremaw", "Diremaw Legs")
	CadastrarCriaturaComDrop(db, "Blue Djin", "Dirty Turban")
	CadastrarCriaturaComDrop(db, "Crypt Defiler", "Dirty Turban")
	CadastrarCriaturaComDrop(db, "Grave Robber", "Dirty Turban")
	CadastrarCriaturaComDrop(db, "Green Djinn", "Dirty Turban")
	CadastrarCriaturaComDrop(db, "Nomad", "Dirty Turban")
	CadastrarCriaturaComDrop(db, "Distorted Phantom", "Distorted Heart")
	CadastrarCriaturaComDrop(db, "Distorted Phantom", "Distorted Robe")
	CadastrarCriaturaComDrop(db, "Behemoth", "Double Axe")
	CadastrarCriaturaComDrop(db, "Black Knight", "Double Axe")
	CadastrarCriaturaComDrop(db, "Cyclops Smith", "Double Axe")
	CadastrarCriaturaComDrop(db, "Diabolic Imp", "Double Axe")
	CadastrarCriaturaComDrop(db, "Dragon", "Double Axe")
	CadastrarCriaturaComDrop(db, "Dwarf Guard", "Double Axe")
	CadastrarCriaturaComDrop(db, "Fire Devil", "Double Axe")
	CadastrarCriaturaComDrop(db, "Golgordan", "Double Axe")
	CadastrarCriaturaComDrop(db, "Latrivan", "Double Axe")
	CadastrarCriaturaComDrop(db, "Lethal Lissy", "Double Axe")
	CadastrarCriaturaComDrop(db, "Minotaur Guard", "Double Axe")
	CadastrarCriaturaComDrop(db, "Quara Predator", "Double Axe")
	CadastrarCriaturaComDrop(db, "Quara Predator Scout", "Double Axe")
	CadastrarCriaturaComDrop(db, "Stonecracker", "Double Axe")
	CadastrarCriaturaComDrop(db, "The Horned Fox", "Double Axe")
	CadastrarCriaturaComDrop(db, "Valkyrie", "Double Axe")
	CadastrarCriaturaComDrop(db, "Ferumbras", "Double Axe")
	CadastrarCriaturaComDrop(db, "General Murius", "Double Axe")
	CadastrarCriaturaComDrop(db, "Ghazbaran", "Double Axe")
	CadastrarCriaturaComDrop(db, "Grand Mother Foulscale", "Double Axe")
	CadastrarCriaturaComDrop(db, "Morgaroth", "Double Axe")
	CadastrarCriaturaComDrop(db, "Mr. Punish", "Double Axe")
	CadastrarCriaturaComDrop(db, "Orshabaal", "Double Axe")
	CadastrarCriaturaComDrop(db, "Tazhadur", "Double Axe")
	CadastrarCriaturaComDrop(db, "Leaf Golem", "Dowser")
	CadastrarCriaturaComDrop(db, "Wilting Leaf Golem", "Dowser")
	CadastrarCriaturaComDrop(db, "Dragolisk", "Dragolisk Eye")
	CadastrarCriaturaComDrop(db, "Dragolisk", "Dragolisk Poison Gland")
	CadastrarCriaturaComDrop(db, "Bulltaur Brute", "Dragon Hammer")
	CadastrarCriaturaComDrop(db, "Dragon", "Dragon Hammer")
	CadastrarCriaturaComDrop(db, "Orc Warlord", "Dragon Hammer")
	CadastrarCriaturaComDrop(db, "Grand Mother Foulscale", "Dragon Hammer")
	CadastrarCriaturaComDrop(db, "Orshabaal", "Dragon Hammer")
	CadastrarCriaturaComDrop(db, "Tazhadur", "Dragon Hammer")
	CadastrarCriaturaComDrop(db, "Lizard Dragon Priest", "Dragon Priest's Wandtip")
	CadastrarCriaturaComDrop(db, "Flamecaller Zazrak", "Dragon Priest's Wandtip")
	CadastrarCriaturaComDrop(db, "Dragon Lord", "Dragon Slayer")
	CadastrarCriaturaComDrop(db, "Eldritch Dragon Lord", "Dragon Slayer")
	CadastrarCriaturaComDrop(db, "Frost Dragon", "Dragon Slayer")
	CadastrarCriaturaComDrop(db, "Inkwing", "Dragon Slayer")
	CadastrarCriaturaComDrop(db, "Ushuriel", "Dragon Slayer")
	CadastrarCriaturaComDrop(db, "Undead Dragon", "Dragon Slayer")
	CadastrarCriaturaComDrop(db, "Albino Dragon", "Dragon Slayer")
	CadastrarCriaturaComDrop(db, "Haunted Dragon", "Dragon Slayer")
	CadastrarCriaturaComDrop(db, "Soul of Dragonking", "Dragon Tongue")
	CadastrarCriaturaComDrop(db, "Zyrtach", "Dragon Tongue")
	CadastrarCriaturaComDrop(db, "Wardragon", "Dragon Tongue")
	CadastrarCriaturaComDrop(db, "Gelidrazah the Frozen", "Dragon Tongue")
	CadastrarCriaturaComDrop(db, "Ice Dragon", "Dragon Tongue")
	CadastrarCriaturaComDrop(db, "Kalyassa", "Dragon Tongue")
	CadastrarCriaturaComDrop(db, "Tazhadur", "Dragon Tongue")
	CadastrarCriaturaComDrop(db, "Zorvorax", "Dragon Tongue")
	CadastrarCriaturaComDrop(db, "Dragolisk", "Dragon's Tail")
	CadastrarCriaturaComDrop(db, "Dragon", "Dragon's Tail")
	CadastrarCriaturaComDrop(db, "Dragon Hatchling", "Dragon's Tail")
	CadastrarCriaturaComDrop(db, "Draken Elite", "Draken Wristbands")
	CadastrarCriaturaComDrop(db, "Paiz the Pauperizer", "Draken Wristbands")
	CadastrarCriaturaComDrop(db, "Crazed Summer Rearguard", "Dream Essence Egg")
	CadastrarCriaturaComDrop(db, "Crazed Summer Vanguard", "Dream Essence Egg")
	CadastrarCriaturaComDrop(db, "Crazed Winter Rearguard", "Dream Essence Egg")
	CadastrarCriaturaComDrop(db, "Insane Siren", "Dream Essence Egg")
	CadastrarCriaturaComDrop(db, "Soul-Broken Harbinger", "Dream Essence Egg")
	CadastrarCriaturaComDrop(db, "Insectoid Worker", "Dung Ball")
	CadastrarCriaturaComDrop(db, "Mindmasher", "Dung Ball")
	CadastrarCriaturaComDrop(db, "Corym Charlatan", "Earflap")
	CadastrarCriaturaComDrop(db, "Corym Skirmisher", "Earflap")
	CadastrarCriaturaComDrop(db, "Corym Vanguard", "Earflap")
	CadastrarCriaturaComDrop(db, "Elder Bonelord", "Elder Bonelord Tentacle")
	CadastrarCriaturaComDrop(db, "Crazed Summer Rearguard", "Elven Astral Observer")
	CadastrarCriaturaComDrop(db, "Crazed Summer Vanguard", "Elven Astral Observer")
	CadastrarCriaturaComDrop(db, "Crazed Winter Rearguard", "Elven Astral Observer")
	CadastrarCriaturaComDrop(db, "Elf Arcanist", "Elven Astral Observer")
	CadastrarCriaturaComDrop(db, "Dharalion", "Elven Astral Observer")
	CadastrarCriaturaComDrop(db, "Emerald Tortoise", "Emerald Tortoise Shell")
	CadastrarCriaturaComDrop(db, "Black Sphinx Acolyte", "Empty Honey Glass")
	CadastrarCriaturaComDrop(db, "Burning Gladiator", "Empty Honey Glass")
	CadastrarCriaturaComDrop(db, "Priestess Of The Wild Sun", "Empty Honey Glass")
	CadastrarCriaturaComDrop(db, "Bulltaur Alchemist", "Encrypted Notes")
	CadastrarCriaturaComDrop(db, "Brain Squid", "Energy Ball")
	CadastrarCriaturaComDrop(db, "Dread Intruder", "Energy Ball")
	CadastrarCriaturaComDrop(db, "Energetic Book", "Energy Ball")
	CadastrarCriaturaComDrop(db, "Outburst", "Energy Ball")
	CadastrarCriaturaComDrop(db, "Flimsy Lost Soul", "Ensouled Essence")
	CadastrarCriaturaComDrop(db, "Freakish Lost Soul", "Ensouled Essence")
	CadastrarCriaturaComDrop(db, "Mean Lost Soul", "Ensouled Essence")
	CadastrarCriaturaComDrop(db, "Arachnophobica", "Essence of a Bad Dream")
	CadastrarCriaturaComDrop(db, "Nightmare", "Essence of a Bad Dream")
	CadastrarCriaturaComDrop(db, "Nightmare Scion", "Essence of a Bad Dream")
	CadastrarCriaturaComDrop(db, "Thanatursus", "Essence of a Bad Dream")
	CadastrarCriaturaComDrop(db, "Tormentor", "Essence of a Bad Dream")
	CadastrarCriaturaComDrop(db, "Exalted Core", "(Nenhuma Criatura Dropa)")
	CadastrarCriaturaComDrop(db, "Execowtioner", "Execowtioner Mask")
	CadastrarCriaturaComDrop(db, "Deathling Scout", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Deathling Spellsinger", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Deepling Brawler", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Deepling Elite", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Deepling Guard", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Deepling Master Librarian", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Deepling Scout", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Deepling Spellsinger", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Deepling Tyrant", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Deepling Warrior", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Deepling Worker", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Shark", "Eye of a Deepling")
	CadastrarCriaturaComDrop(db, "Weeper", "Eye of a Weeper")
	CadastrarCriaturaComDrop(db, "Draken Abomination", "Eye of Corruption")
	CadastrarCriaturaComDrop(db, "Eyeless Devourer", "Eyeless Devourer Legs")
	CadastrarCriaturaComDrop(db, "Eyeless Devourer", "Eyeless Devourer Maw")
	CadastrarCriaturaComDrop(db, "Eyeless Devourer", "Eyeless Devourer Tongue")
	CadastrarCriaturaComDrop(db, "Burning Gladiator", "Fafnar Symbol")
	CadastrarCriaturaComDrop(db, "Priestess Of The Wild Sun", "Fafnar Symbol")
	CadastrarCriaturaComDrop(db, "Falcon Paladin", "Falcon Crest")
	CadastrarCriaturaComDrop(db, "Falcon Knight", "Falcon Crest")
	CadastrarCriaturaComDrop(db, "Grand Commander Soeren", "Falcon Crest")
	CadastrarCriaturaComDrop(db, "Barkless Fanatic", "Fig Leaf")
	CadastrarCriaturaComDrop(db, "Barkless Devotee", "Fig Leaf")
	CadastrarCriaturaComDrop(db, "Ravenous Hunger", "Fig Leaf")
	CadastrarCriaturaComDrop(db, "Leaf Golem", "Fir Cone")
	CadastrarCriaturaComDrop(db, "Wilting Leaf Golem", "Fir Cone")
	CadastrarCriaturaComDrop(db, "Angry Demon", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Arbaziloth", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Brachiodemom", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Demon", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Essence of Malice", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Feral Sphinx", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Golgordan", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Guardian of Tales", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Hellfire Fighter", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Infernal Phantom", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Insane Siren", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Latrivan", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Lava Golem", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Lost Basher", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Lost Berserk", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Mahrdis", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Mazoran", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Mean Lost Soul", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Rage Squid", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Sulphider", "Fire Axe")
	CadastrarCriaturaComDrop(db, "The Count of The Core", "Fire Axe")
	CadastrarCriaturaComDrop(db, "The Duke Of The Depths", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Vexclaw", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Weeper", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Furyosa", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Orshabaal", "Fire Axe")
	CadastrarCriaturaComDrop(db, "The Imperor", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Minishabaal", "Fire Axe")
	CadastrarCriaturaComDrop(db, "Betrayed Wraith", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Burning Book", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Dark Torturer", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Dawnfire Asura", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Diabolic Imp", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Falcon Knight", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Floating Savant", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Frost Flower Asura", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Fury", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Grim Reaper", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Grimeleech", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Hand of Cursed Fate", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Hellflayeer", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Hellhound", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Juggernaut", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Midnight Asura", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Nightmare", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "True Dawnfire Asura", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "True Midnight Asura", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "True Feverbloom Asura", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "True Frost Flower Asura", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Fluffy", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Furyosa", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Grand Chaplain Gaunder", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Kerberos", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Kusuma", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Mazoran", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Plagirath", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Preceptor Lazare", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Ragiaz", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Razzagorn", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Shulgrax", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Tarbaz", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "The Blazing Rose", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "The Diamond Blossom", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "The Flaming Orchid", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "The Lily of Night", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "The Moonlight Aster", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "The Moonsnow Magnolia", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "The Winter Bloom", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Tormentor", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Zamulosh", "Flask of Demonic Blood")
	CadastrarCriaturaComDrop(db, "Foam Stalker", "Floatsam")
	CadastrarCriaturaComDrop(db, "Venerable Foam Stalker", "Floatsam")
	CadastrarCriaturaComDrop(db, "Afflicted Strider", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Converter", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Dawnfire Asura", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Draken Spellweaver", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Girtablilu Warrior", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Harpy", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Lavafungus", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Lizard Dragon Priest", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Lumbering Carnivor", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Nightmare Scion", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Pirat Cutthroat", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Reality Reaver", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Sea Serpent", "Focus Cape")
	CadastrarCriaturaComDrop(db, "stabilizing Reality Reaver", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Tremendous Tyrant", "Focus Cape")
	CadastrarCriaturaComDrop(db, "True Dawnfire Asura", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Wyrm", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Amenef the Burning", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Captain Jones", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Hellgorak", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Raging Mage", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Reflection of a Mage", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Sister Hetai", "Focus Cape")
	CadastrarCriaturaComDrop(db, "Fox", "Fox Paw")
	CadastrarCriaturaComDrop(db, "Werefox", "Fox Paw")
	CadastrarCriaturaComDrop(db, "Black Vixen", "Fox Paw")
	CadastrarCriaturaComDrop(db, "Animated Guzzlemaw", "Frazzle Tongue")
	CadastrarCriaturaComDrop(db, "Frazzlemaw", "Frazzle Tongue")
	CadastrarCriaturaComDrop(db, "Guzzlemaw", "Frazzle Tongue")
	CadastrarCriaturaComDrop(db, "Nibblemaw", "Frazzle Tongue")
	CadastrarCriaturaComDrop(db, "Weakened Frazzlemaw", "Frazzle Tongue")
	CadastrarCriaturaComDrop(db, "Mawhawk", "Frazzle Tongue")
	CadastrarCriaturaComDrop(db, "Reflection of Mawhawk", "Frazzle Tongue")
	CadastrarCriaturaComDrop(db, "Brain Squid", "Frozen Lightning")
	CadastrarCriaturaComDrop(db, "Dread Intruder", "Frozen Lightning")
	CadastrarCriaturaComDrop(db, "Anomaly", "Frozen Lightning")
	CadastrarCriaturaComDrop(db, "Rupture", "Frozen Lightning")
	CadastrarCriaturaComDrop(db, "Mazzinor", "Frozen Lightning")
	CadastrarCriaturaComDrop(db, "Adult Goanna", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Blemished Spawn", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Capricious Phantom", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Cave Chimera", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Cunning Werepanter", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Girtablilu Warrior", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Lumbering Carnivor", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Raubritter Skirmisher", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Rotten Golem", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Sun-marked Goanna", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Turbulent Elemental", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Varnished Diremaw", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Werebear", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Wereboar", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Werecrocodile", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Werephanter", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Winged Jaracal", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Young Goanna", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Bloodback", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Feroxa", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Michael the Stalwart", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Owin", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Rakesh Moonfang", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Shadowpelt", "Fur Armor")
	CadastrarCriaturaComDrop(db, "Animated Mummy", "Gauze Bandage")
	CadastrarCriaturaComDrop(db, "Elder Mummy", "Gauze Bandage")
	CadastrarCriaturaComDrop(db, "Mummy", "Gauze Bandage")
	CadastrarCriaturaComDrop(db, "Mahatheb", "Gauze Bandage")
	CadastrarCriaturaComDrop(db, "Ghastly Dragon", "Ghastly Dragon Head")
	CadastrarCriaturaComDrop(db, "Ethershreck", "Ghastly Dragon Head")
	CadastrarCriaturaComDrop(db, "Hatebreeder", "Ghastly Dragon Head")
	CadastrarCriaturaComDrop(db, "Animated Moohtant", "Giant Pacifier")
	CadastrarCriaturaComDrop(db, "Moohtant", "Giant Pacifier")
	CadastrarCriaturaComDrop(db, "Bullwark", "Giant Pacifier")
	CadastrarCriaturaComDrop(db, "Moohtant Wallbreaker", "Giant Pacifier")
	CadastrarCriaturaComDrop(db, "Creepy Crawler", "Giant Tusk")
	CadastrarCriaturaComDrop(db, "Crypt Fiend", "Giant Tusk")
	CadastrarCriaturaComDrop(db, "Amazon", "Girlish Hair Decoration")
	CadastrarCriaturaComDrop(db, "Valkyrie", "Girlish Hair Decoration")
	CadastrarCriaturaComDrop(db, "Girtablilu Warrior", "Girtablilu Warrior Carapace")
	CadastrarCriaturaComDrop(db, "Animated Feather", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Animated Snowman", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Crazed Winter Rearguard", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Crystal Spider", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Ice Dragon", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Ice Golem", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Icecold Book", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Memory of a Dwarf", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Monk's Apparition", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Mycobiontic Beetle", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Paladin's Apparition", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Seacrest Serpent", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Silverfrost Sentinel", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Squid Warden", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Court Warlock", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Earl Osam", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Gelidrazah the Frozen", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Hirintror", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Ice Horror", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Neferi the Spy", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Shardhead", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "The Bloodweb", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Zushuka", "Glacier Mask")
	CadastrarCriaturaComDrop(db, "Crazed Winter Rearguard", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Crazed Winter Vanguard", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Druid's Apparition", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Girtablilu Warrior", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Google Cake", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Hazardous Phantom", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Icecold Book", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Many Faces", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Quara Pincher", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Quara Predator", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Quara Raider", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Renegade Quara Pincher", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Renegade Quara Predator", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Schiach", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Squid Warden", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Tremendous Tyrant", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Turbulent Elemental", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Court Warlock", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "King Zelos", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Srezz Yellow Eyes", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Tarbaz", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "The Time Guardian", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "The Winter Bloom", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Utua Stone Sting", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Yakchal", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Zushuka", "Glacier Robe")
	CadastrarCriaturaComDrop(db, "Bluebeak", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Foam Stalker", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Ice Witch", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Icecold Book", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Many Faces", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Seacrest Serpent", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Soul-broken Harbinger", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Two-Headed Turtle", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Usurper Archer", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Varnished Diremaw", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Venerable Foam Stalker", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Hirintror", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Neferi the Spy", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Zushuka", "Glacier Shoes")
	CadastrarCriaturaComDrop(db, "Acid Blob", "Glob of Acid Slime")
	CadastrarCriaturaComDrop(db, "Defile", "Glob of Acid Slime")
	CadastrarCriaturaComDrop(db, "Stonerefiner", "Glob of Acid Slime")
	CadastrarCriaturaComDrop(db, "Devourer", "Glob of Glooth")
	CadastrarCriaturaComDrop(db, "Glooth Blob", "Glob of Glooth")
	CadastrarCriaturaComDrop(db, "Rot Elemental", "Glob of Glooth")
	CadastrarCriaturaComDrop(db, "Death Blob", "Glob of Tar")
	CadastrarCriaturaComDrop(db, "Defiler", "Glob of Tar")
	CadastrarCriaturaComDrop(db, "Blood Beast", "Glooth Axe")
	CadastrarCriaturaComDrop(db, "Devourer", "Glooth Axe")
	CadastrarCriaturaComDrop(db, "Glooth Anemone", "Glooth Axe")
	CadastrarCriaturaComDrop(db, "Glooth Bandit", "Glooth Axe")
	CadastrarCriaturaComDrop(db, "Glooth Blob", "Glooth Axe")
	CadastrarCriaturaComDrop(db, "Glooth Brigand", "Glooth Axe")
	CadastrarCriaturaComDrop(db, "Glooth Golem", "Glooth Axe")
	CadastrarCriaturaComDrop(db, "Rot Elemental", "Glooth Axe")
	CadastrarCriaturaComDrop(db, "Glooth Fairy", "Glooth Axe")
	CadastrarCriaturaComDrop(db, "Lisa", "Glooth Axe")
	CadastrarCriaturaComDrop(db, "Blood Beast", "Glooth Blade")
	CadastrarCriaturaComDrop(db, "Devourer", "Glooth Blade")
	CadastrarCriaturaComDrop(db, "Glooth Anemone", "Glooth Blade")
	CadastrarCriaturaComDrop(db, "Glooth Bandit", "Glooth Blade")
	CadastrarCriaturaComDrop(db, "Glooth Blob", "Glooth Blade")
	CadastrarCriaturaComDrop(db, "Glooth Brigand", "Glooth Blade")
	CadastrarCriaturaComDrop(db, "Glooth Golem", "Glooth Blade")
	CadastrarCriaturaComDrop(db, "Glooth Fairy", "Glooth Blade")
	CadastrarCriaturaComDrop(db, "Lisa", "Glooth Blade")
	CadastrarCriaturaComDrop(db, "Devourer", "Glooth Cape")
	CadastrarCriaturaComDrop(db, "Glooth Anemone", "Glooth Cape")
	CadastrarCriaturaComDrop(db, "Glooth Bandit", "Glooth Cape")
	CadastrarCriaturaComDrop(db, "Glooth Fairy", "Glooth Cape")
	CadastrarCriaturaComDrop(db, "Lisa", "Glooth Cape")
	CadastrarCriaturaComDrop(db, "Tremor Worm", "Glooth Cape")
	CadastrarCriaturaComDrop(db, "Blood Beast", "Glooth Club")
	CadastrarCriaturaComDrop(db, "Devourer", "Glooth Club")
	CadastrarCriaturaComDrop(db, "Glooth Anemone", "Glooth Club")
	CadastrarCriaturaComDrop(db, "Glooth Bandit", "Glooth Club")
	CadastrarCriaturaComDrop(db, "Glooth Blob", "Glooth Club")
	CadastrarCriaturaComDrop(db, "Glooth Brigand", "Glooth Club")
	CadastrarCriaturaComDrop(db, "Glooth Golem", "Glooth Club")
	CadastrarCriaturaComDrop(db, "Glooth Fairy", "Glooth Club")
	CadastrarCriaturaComDrop(db, "Lisa", "Glooth Club")
	CadastrarCriaturaComDrop(db, "Glooth Golem", "Glooth Injection Tube")
	CadastrarCriaturaComDrop(db, "Glooth Fairy", "Glooth Injection Tube")
	CadastrarCriaturaComDrop(db, "Bashmu", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Bellicose", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Bellicose Orger", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Enfeebled Silencer", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Enraged Crystal", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Enraged Crystal Golem", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Enslaved Dwarf", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Infernal Phantom", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Lumbering Carnivor", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Mutated Tiger", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Orewalker", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Silencer", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Stone Devourer", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Werecrocodile", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Werelion", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Feroxa", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Ghazbaran", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Maior Domus", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Weakened Shlorg", "Glorious Axe")
	CadastrarCriaturaComDrop(db, "Animated Feather", "Glowing Rune")
	CadastrarCriaturaComDrop(db, "Biting Book", "Glowing Rune")
	CadastrarCriaturaComDrop(db, "Brain Squid", "Glowing Rune")
	CadastrarCriaturaComDrop(db, "Energetic Book", "Glowing Rune")
	CadastrarCriaturaComDrop(db, "Energuardian of Tales", "Glowing Rune")
	CadastrarCriaturaComDrop(db, "Guardian of Tales", "Glowing Rune")
	CadastrarCriaturaComDrop(db, "Knowledge Elemental", "Glowing Rune")
	CadastrarCriaturaComDrop(db, "Rage Squid", "Glowing Rune")
	CadastrarCriaturaComDrop(db, "Squid Warden", "Glowing Rune")
	CadastrarCriaturaComDrop(db, "Adult Goanna", "Goanna Claw")
	CadastrarCriaturaComDrop(db, "Young Goanna", "Goanna Claw")
	CadastrarCriaturaComDrop(db, "Adult Goanna", "Goanna Meat")
	CadastrarCriaturaComDrop(db, "Sun-marked Goanna", "Goanna Meat")
	CadastrarCriaturaComDrop(db, "Young Goanna", "Goanna Meat")
	CadastrarCriaturaComDrop(db, "Pirate Cook", "Gold Tooth")
	CadastrarCriaturaComDrop(db, "Pirate Gunner", "Gold Tooth")
	CadastrarCriaturaComDrop(db, "Pirate Navigator", "Gold Tooth")
	CadastrarCriaturaComDrop(db, "Pirate Quartermaster", "Gold Tooth")
	CadastrarCriaturaComDrop(db, "Sea Captain", "Gold Tooth")
	CadastrarCriaturaComDrop(db, "Devoted Radiant Inquisitor", "Golden Belt")
	CadastrarCriaturaComDrop(db, "Radiant Inquisitor", "Golden Belt")
	CadastrarCriaturaComDrop(db, "Angry Demon", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Blightwalker", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Boogy", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Cunning Werepanther", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Demon", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Priestess of the Wild Sun", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Werepanther", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Arbaziloth", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Arbaziloth Hard", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Latrivan", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Orshabaal", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Rakesh Moonfang", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Rotrender Scourge of Azzilon", "Golden Sickle")
	CadastrarCriaturaComDrop(db, "Feral Werecrocodile", "Golden Sun Coin")
	CadastrarCriaturaComDrop(db, "Werecrocodile", "Golden Sun Coin")
	CadastrarCriaturaComDrop(db, "Ayana The Crunsib Curse", "Golden Sun Coin")
	CadastrarCriaturaComDrop(db, "Gore Horn", "Gore Horn")
	CadastrarCriaturaComDrop(db, "Gorerilla Mane", "Gorerilla")
	CadastrarCriaturaComDrop(db, "Gorerilla Tail", "Gorerilla")
	CadastrarCriaturaComDrop(db, "Gorger Antlers", "Gorger Inferniarch")
	CadastrarCriaturaComDrop(db, "Grappling Hook", "Pirat Scoundrel")
	CadastrarCriaturaComDrop(db, "Green Bandage", "Putrid Mummy")
	CadastrarCriaturaComDrop(db, "Burning Book", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Choking Fear", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Cult Enforcer", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Demon Skeleton", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Diabolic Imp", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Energy Elemental", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Enslaved Dwarf", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Fire Devil", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Knowledge Elemental", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Lost Berserker", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Lost Exile", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Lost Husher", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Minotaur Invader", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Mooh'Tah Warrior", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Mutated Tiger", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Spiky Carnivor", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Undead Minion", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Vicious Squire", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Annihilon", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Minishabaal", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Terofar", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "The Imperor", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Tyrn", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Zavarash", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Zomba", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Zulazza the Corruptor", "Guardian Shield")
	CadastrarCriaturaComDrop(db, "Animated Cyclops", "Halberd")
	CadastrarCriaturaComDrop(db, "Barbarian Bloodwalker", "Halberd")
	CadastrarCriaturaComDrop(db, "Cult Enforcer","Halberd")
	CadastrarCriaturaComDrop(db, "Cyclops","Halberd")
	CadastrarCriaturaComDrop(db, "Cyclops Drone","Halberd")
	CadastrarCriaturaComDrop(db, "Foam Stalker","Halberd")
	CadastrarCriaturaComDrop(db, "Frost Giant","Halberd")
	CadastrarCriaturaComDrop(db, "Golden Servant","Halberd")
	CadastrarCriaturaComDrop(db, "Golden Servant Replica","Halberd")
	CadastrarCriaturaComDrop(db, "Hacker","Halberd")
	CadastrarCriaturaComDrop(db, "Iron Servant","Halberd")
	CadastrarCriaturaComDrop(db, "Iron Servant Replica","Halberd")
	CadastrarCriaturaComDrop(db, "Lizard Sentinel","Halberd")
	CadastrarCriaturaComDrop(db, "Mutated Rat","Halberd")
	CadastrarCriaturaComDrop(db, "Orc Berserker","Halberd")
	CadastrarCriaturaComDrop(db, "Orc Cult Inquisitor","Halberd")
	CadastrarCriaturaComDrop(db, "Orc Cult Inquisitor","Halberd")
	CadastrarCriaturaComDrop(db, "Quara Mantassin","Halberd")
	CadastrarCriaturaComDrop(db, "Quara Pincher","Halberd")
	CadastrarCriaturaComDrop(db, "Quara Pincher","Halberd")
	CadastrarCriaturaComDrop(db, "Quara Pincher Scout","Halberd")
	CadastrarCriaturaComDrop(db, "Renegade Quara Pincher","Halberd")
	CadastrarCriaturaComDrop(db, "Thanatursus","Halberd")
	CadastrarCriaturaComDrop(db, "Venerable Foam Stalker","Halberd")
	CadastrarCriaturaComDrop(db, "Vicious Squire","Halberd")
	CadastrarCriaturaComDrop(db, "Wailing Widow","Halberd")
	CadastrarCriaturaComDrop(db, "Werehyaena","Halberd")
	CadastrarCriaturaComDrop(db, "Werewolf","Halberd")
	CadastrarCriaturaComDrop(db, "Zombie","Halberd")
	CadastrarCriaturaComDrop(db, "Annihilon","Halberd")
	CadastrarCriaturaComDrop(db, "Black Knight","Halberd")
	CadastrarCriaturaComDrop(db, "Esmeralda","Halberd")
	CadastrarCriaturaComDrop(db, "Stonerefiner","Half-Digested Stones")
	CadastrarCriaturaComDrop(db, "Zombie","Half-Eaten Brain")
	CadastrarCriaturaComDrop(db, "Brachiodemon","Hand")
	CadastrarCriaturaComDrop(db, "Harpy","Harpy Feathers")
	CadastrarCriaturaComDrop(db, "Brachiodemon","Head")
	CadastrarCriaturaComDrop(db, "Many Faces","Head")
	CadastrarCriaturaComDrop(db, "Headpecker","Headpecker Beak")
	CadastrarCriaturaComDrop(db, "Headpecker","Headpecker Feather")
	CadastrarCriaturaComDrop(db, "Norcferatu Heartless","Heart Amphora")
	CadastrarCriaturaComDrop(db, "Cobra Assassin","Heavy Machete")
	CadastrarCriaturaComDrop(db, "Cyclops Smith","Heavy Machete")
	CadastrarCriaturaComDrop(db, "Efreet","Heavy Machete")
	CadastrarCriaturaComDrop(db, "Marid","Heavy Machete")
	CadastrarCriaturaComDrop(db, "Menacing Carnivor","Heavy Machete")
	CadastrarCriaturaComDrop(db, "Fahim The Wise","Heavy Machete")
	CadastrarCriaturaComDrop(db, "Merikh the Slaughterer","Heavy Machete")
	CadastrarCriaturaComDrop(db, "Deathling Scout","Heavy Trident")
	CadastrarCriaturaComDrop(db, "Deathling Spellsinger","Heavy Trident")
	CadastrarCriaturaComDrop(db, "Deathling Brawler","Heavy Trident")
	CadastrarCriaturaComDrop(db, "Deepling Elite","Heavy Trident")
	CadastrarCriaturaComDrop(db, "Deepling Guard","Heavy Trident")
	CadastrarCriaturaComDrop(db, "Deepling Scout","Heavy Trident")
	CadastrarCriaturaComDrop(db, "Deepling Tyrant","Heavy Trident")
	CadastrarCriaturaComDrop(db, "Deepling Warrior","Heavy Trident")
	CadastrarCriaturaComDrop(db, "Deepling Worker","Heavy Trident")
	CadastrarCriaturaComDrop(db, "Neutral Deepling Warrior","Heavy Trident")
	CadastrarCriaturaComDrop(db, "Hellhound","Hellhound Slobber")
	CadastrarCriaturaComDrop(db, "Kerberos","Hellhound Slobber")
	CadastrarCriaturaComDrop(db, "Choking Fear","Hemp Rope")
	CadastrarCriaturaComDrop(db, "Angry Sugar Fairy","Hibiscus Dress")
	CadastrarCriaturaComDrop(db, "Nymph","Hibiscus Dress")
	CadastrarCriaturaComDrop(db, "Vampire Bride","Hibiscus Dress")
	CadastrarCriaturaComDrop(db, "Wyrm","Hibiscus Dress")
	CadastrarCriaturaComDrop(db, "Boreth","Hibiscus Dress")
	CadastrarCriaturaComDrop(db, "Hideous Fungus","Hideous Chunk")
	CadastrarCriaturaComDrop(db, "Lizard High Guard","High Guard Flag")
	CadastrarCriaturaComDrop(db, "Lizard High Guard","High Guard Shoulderplates")
	CadastrarCriaturaComDrop(db, "Flickering Spirit Elemental","Holy Ash")
	CadastrarCriaturaComDrop(db, "Lost Exile","Holy Ash")
	CadastrarCriaturaComDrop(db, "Lost Husher","Holy Ash")
	CadastrarCriaturaComDrop(db, "Psychic Spirit Elemental","Holy Ash")
	CadastrarCriaturaComDrop(db, "Phosphorus","Holy Ash")
	CadastrarCriaturaComDrop(db, "Spirit Overlord","Holy Ash")
	CadastrarCriaturaComDrop(db, "Blood Hand","Horoscope")
	CadastrarCriaturaComDrop(db, "Blood Priest","Horoscope")
	CadastrarCriaturaComDrop(db, "Shadow Pupil","Horoscope")
	CadastrarCriaturaComDrop(db, "Dark Canisylvan","Human Teeth")
	CadastrarCriaturaComDrop(db, "Hulking Carnisylvan","Human Teeth")
	CadastrarCriaturaComDrop(db, "Poisonous Carnisylvan","Human Teeth")
	CadastrarCriaturaComDrop(db, "Humongous Fungus","Humongous Chunk")
	CadastrarCriaturaComDrop(db, "Hydra","Hydra Head")
	CadastrarCriaturaComDrop(db, "Lion Hydra","Hydra Head")
	CadastrarCriaturaComDrop(db, "Two-Headed Turtle","Hydrophytes")
	CadastrarCriaturaComDrop(db, "Crazed Winter Rearguard","Ice Flower")
	CadastrarCriaturaComDrop(db, "Crazed Winter Vanguard","Ice Flower")
	CadastrarCriaturaComDrop(db, "Soul-broken Harbinger","Ice Flower")
	CadastrarCriaturaComDrop(db, "Bulltaur Forgepriest","Idol of the Forge")
	CadastrarCriaturaComDrop(db, "Infernal Phantom","Infernal Heart")
	CadastrarCriaturaComDrop(db, "Infernal Phantom","Infernal Robe")
	CadastrarCriaturaComDrop(db, "Infernoid Blob","Infernoid Ember")
	CadastrarCriaturaComDrop(db, "Infernoid Hound","Infernoid Ember")
	CadastrarCriaturaComDrop(db, "Infernoid Soul","Infernoid Ember")
	CadastrarCriaturaComDrop(db, "Infernoid Spiritual","Infernoid Ember")
	CadastrarCriaturaComDrop(db, "Herald of Fire","Infernoid Ember")
	CadastrarCriaturaComDrop(db, "Brain Squid","Inkwell")
	CadastrarCriaturaComDrop(db, "Ink Blob","Inkwell")
	CadastrarCriaturaComDrop(db, "Ink Splash","Inkwell")
	CadastrarCriaturaComDrop(db, "Rage Squid","Inkwell")
	CadastrarCriaturaComDrop(db, "Squid Warden","Inkwell")
	CadastrarCriaturaComDrop(db, "Brain Squid", "Instable Proto Matter")
	CadastrarCriaturaComDrop(db, "Dread Intruder", "Instable Proto Matter")
	CadastrarCriaturaComDrop(db, "Outburst", "Instable Proto Matter")
	CadastrarCriaturaComDrop(db, "Werelion","Ivory Carving")
	CadastrarCriaturaComDrop(db, "Werelioness","Ivory Carving")
	CadastrarCriaturaComDrop(db, "Bony Seal Devil","Jaws")
	CadastrarCriaturaComDrop(db, "Deepling Master Librarian", "Key to the Drowned Librabry")
	CadastrarCriaturaComDrop(db, "Deepling Spellsinger", "Key to the Drowned Librabry")
	CadastrarCriaturaComDrop(db, "Assassin","Knife")
	CadastrarCriaturaComDrop(db, "Barbarian Headsplitter","Knife")
	CadastrarCriaturaComDrop(db, "Barbarian Skullhunter","Knife")
	CadastrarCriaturaComDrop(db, "Cobra Assassin","Knife")
	CadastrarCriaturaComDrop(db, "Crazed Summer Vanguard","Knife")
	CadastrarCriaturaComDrop(db, "Headpecker","Knife")
	CadastrarCriaturaComDrop(db, "Smuggler","Knife")
	CadastrarCriaturaComDrop(db, "Undead Prospector","Knife")
	CadastrarCriaturaComDrop(db, "Usurper Archer","Knife")
	CadastrarCriaturaComDrop(db, "Werehyaena","Knife")
	CadastrarCriaturaComDrop(db, "Ancient lion Knight","Knife")
	CadastrarCriaturaComDrop(db, "Apprentice Sheng","Knife")
	CadastrarCriaturaComDrop(db, "Faceless Bane","Knife")
	CadastrarCriaturaComDrop(db, "Afflicted Strider","Knight Axe")
	CadastrarCriaturaComDrop(db, "Blemished Spawn","Knight Axe")
	CadastrarCriaturaComDrop(db, "Crusader","Knight Axe")
	CadastrarCriaturaComDrop(db, "Execowtioner","Knight Axe")
	CadastrarCriaturaComDrop(db, "Girtablilu Warrior","Knight Axe")
	CadastrarCriaturaComDrop(db, "Hellhound","Knight Axe")
	CadastrarCriaturaComDrop(db, "Hulking Carnisylvan","Knight Axe")
	CadastrarCriaturaComDrop(db, "Lost Basher","Knight Axe")
	CadastrarCriaturaComDrop(db, "Lost Berserker","Knight Axe")
	CadastrarCriaturaComDrop(db, "Lost Exile","Knight Axe")
	CadastrarCriaturaComDrop(db, "Lost Husher","Knight Axe")
	CadastrarCriaturaComDrop(db, "Minotaur Invader","Knight Axe")
	CadastrarCriaturaComDrop(db, "Pirat Cutthroat","Knight Axe")
	CadastrarCriaturaComDrop(db, "Poisonous Carnisylvan","Knight Axe")
	CadastrarCriaturaComDrop(db, "Skeleton Elite Warrior","Knight Axe")
	CadastrarCriaturaComDrop(db, "Thanatursus","Knight Axe")
	CadastrarCriaturaComDrop(db, "Tremendous Tyrant","Knight Axe")
	CadastrarCriaturaComDrop(db, "Undead Elite Gladiator","Knight Axe")
	CadastrarCriaturaComDrop(db, "Undead Gladiator","Knight Axe")
	CadastrarCriaturaComDrop(db, "Amenef the Burning","Knight Axe")
	CadastrarCriaturaComDrop(db, "Black Knight","Knight Axe")
	CadastrarCriaturaComDrop(db, "Fluffy","Knight Axe")
	CadastrarCriaturaComDrop(db, "Kerberos","Knight Axe")
	CadastrarCriaturaComDrop(db, "Morguthis","Knight Axe")
	CadastrarCriaturaComDrop(db, "Neferi the Spy","Knight Axe")
	CadastrarCriaturaComDrop(db, "Sir Leonard","Knight Axe")
	CadastrarCriaturaComDrop(db, "Sir Leopold","Knight Axe")
	CadastrarCriaturaComDrop(db, "The Enraged Thor Knight","Knight Axe")
	CadastrarCriaturaComDrop(db, "Cliff Strider","Knight Legs")
	CadastrarCriaturaComDrop(db, "Crystal Spider","Knight Legs")
	CadastrarCriaturaComDrop(db, "Cult Enforcer","Knight Legs")
	CadastrarCriaturaComDrop(db, "Foam Stalker","Knight Legs")
	CadastrarCriaturaComDrop(db, "Giant Spider","Knight Legs")
	CadastrarCriaturaComDrop(db, "Gore Horn","Knight Legs")
	CadastrarCriaturaComDrop(db, "Hellspawn","Knight Legs")
	CadastrarCriaturaComDrop(db, "Lost Basher","Knight Legs")
	CadastrarCriaturaComDrop(db, "Menacing Carnivor","Knight Legs")
	CadastrarCriaturaComDrop(db, "Mooh'Tah Warrior","Knight Legs")
	CadastrarCriaturaComDrop(db, "Nightmare","Knight Legs")
	CadastrarCriaturaComDrop(db, "Orewalker","Knight Legs")
	CadastrarCriaturaComDrop(db, "Plaguesmith","Knight Legs")
	CadastrarCriaturaComDrop(db, "Soul-broken Harbinger","Knight Legs")
	CadastrarCriaturaComDrop(db, "Sulphur Spouter","Knight Legs")
	CadastrarCriaturaComDrop(db, "Two-Headed Turtle","Knight Legs")
	CadastrarCriaturaComDrop(db, "Usurper Knight","Knight Legs")
	CadastrarCriaturaComDrop(db, "Usurper Warlock","Knight Legs")
	CadastrarCriaturaComDrop(db, "Venerable Foam Stalker","Knight Legs")
	CadastrarCriaturaComDrop(db, "Vicious Squire","Knight Legs")
	CadastrarCriaturaComDrop(db, "Black Knight","Knight Legs")
	CadastrarCriaturaComDrop(db, "Count Vlarkorth","Knight Legs")
	CadastrarCriaturaComDrop(db, "Flameborn","Knight Legs")
	CadastrarCriaturaComDrop(db, "Hellgorak","Knight Legs")
	CadastrarCriaturaComDrop(db, "Hide","Knight Legs")
	CadastrarCriaturaComDrop(db, "Horadron","Knight Legs")
	CadastrarCriaturaComDrop(db, "Mamma Longlegs","Knight Legs")
	CadastrarCriaturaComDrop(db, "Sir Baeloc","Knight Legs")
	CadastrarCriaturaComDrop(db, "Sir Leonard","Knight Legs")
	CadastrarCriaturaComDrop(db, "Sir Leopold","Knight Legs")
	CadastrarCriaturaComDrop(db, "The Bloodweb","Knight Legs")
	CadastrarCriaturaComDrop(db, "The Old Widow","Knight Legs")
	CadastrarCriaturaComDrop(db, "Tormentor","Knight Legs")
	CadastrarCriaturaComDrop(db, "Cursed Ape","Kongra's Shouldpad")
	CadastrarCriaturaComDrop(db, "Kongra","Kongra's Shouldpad")
	CadastrarCriaturaComDrop(db, "Crypt Warden","Lamassu Hoof")
	CadastrarCriaturaComDrop(db, "Lamassu","Lamassu Hoof")
	CadastrarCriaturaComDrop(db, "Lancer Beetle","Lancer Beetle Shell")
	CadastrarCriaturaComDrop(db, "The Blightfather","Lancer Beetle Shell")
	CadastrarCriaturaComDrop(db, "Blood Hand","Lancet")
	CadastrarCriaturaComDrop(db, "Blood Priest","Lancet")
	CadastrarCriaturaComDrop(db, "Lavafungus","Lavafungus Head")
	CadastrarCriaturaComDrop(db, "Lavafungus","Lavafungus Ring")
	CadastrarCriaturaComDrop(db, "Lavaworm","Laworm Jaws")
	CadastrarCriaturaComDrop(db, "Lavaworm","Lavaworm Spike Roots")
	CadastrarCriaturaComDrop(db, "Lavaworm","Lavaworm Spikes")
	CadastrarCriaturaComDrop(db, "Burning Gladiator","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Cursed Prospector","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Elder Wyrm","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Energetic Book","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Juvenile Bashmu","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Lich","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Mercurial Menace","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Pirat Bombardier","Lightning Boots")
	CadastrarCriaturaComDrop(db, "War Golem","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Gravelord Oshuran","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Mazzinor","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Omrafir","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Phosphorus","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Prince Drazzak","Lightning Boots")
	CadastrarCriaturaComDrop(db, "Brain Squid","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Burning Gladiator","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Cloak of Terror","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Courage Leech","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Cunning Werephanter","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Energetic Book","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Evil Prospector","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Giant Spider","Lightning Headband")
	CadastrarCriaturaComDrop(db, "High Voltage Elemental","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Hulking Carnisylvan","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Reality Reaver","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Sphinx","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Stabilizing Reality Reaver","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Tow-Headed Turtle","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Usurper Warlock","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Werelioness","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Anomaly","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Burster","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Court Warlock","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Lord Azaram","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Neferi the Spy","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Outburst","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Phosphorus","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Rakesh Moonfang","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Realityquake","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Rupture","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Sister Hetai","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Tyrn","Lightning Headband")
	CadastrarCriaturaComDrop(db, "World Devourer","Lightning Headband")
	CadastrarCriaturaComDrop(db, "Bulltaur Forgepriest","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Cursed Prospector","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Elder Wyrm","Lightning Robe")
	CadastrarCriaturaComDrop(db, "High Voltage Elemental","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Raubritter Chastener","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Warlock","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Anomaly","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Court Warlock","Lightning Robe")
	CadastrarCriaturaComDrop(db, "King Zelos","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Mad Mage","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Omrafir","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Outburst","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Overseer Osverger","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Phosphorus","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Prince Drazzak","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Realityquake","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Tyrn","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Zarabustor","Lightning Robe")
	CadastrarCriaturaComDrop(db, "Nibblemaw","Lime Tart")
	CadastrarCriaturaComDrop(db, "Sugar Daddy","Lime Tart")
	CadastrarCriaturaComDrop(db, "Liodile","Liodile Fang")
	CadastrarCriaturaComDrop(db, "Usurper Archer","Lion Cloak Patch")
	CadastrarCriaturaComDrop(db, "Usurper Commander","Lion Cloak Patch")
	CadastrarCriaturaComDrop(db, "Usurper Knight","Lion Cloak Patch")
	CadastrarCriaturaComDrop(db, "Usurper Warlock","Lion Cloak Patch")
	CadastrarCriaturaComDrop(db, "Usurper Archer","Lion Crest")
	CadastrarCriaturaComDrop(db, "Usurper Commander","Lion Crest")
	CadastrarCriaturaComDrop(db, "Usurper Knight","Lion Crest")
	CadastrarCriaturaComDrop(db, "Usurper Warlock","Lion Crest")
	CadastrarCriaturaComDrop(db, "Lizard Executioner","Lizard Tail")
	CadastrarCriaturaComDrop(db, "Lizard Henchman","Lizard Tail")
	CadastrarCriaturaComDrop(db, "Lizard Magician","Lizard Tail")
	CadastrarCriaturaComDrop(db, "Lizard Swordmaster","Lizard Tail")
	CadastrarCriaturaComDrop(db, "Lizard Commander","Lizard Tail")
	CadastrarCriaturaComDrop(db, "Devoted Radiant Zealot","Loose Prayer Beads")
	CadastrarCriaturaComDrop(db, "Radiant Zealot","Loose Prayer Beads")
	CadastrarCriaturaComDrop(db, "Lost Basher","Lost Basher's Spike")
	CadastrarCriaturaComDrop(db, "Lost Thrower","Lost Bracers")
	CadastrarCriaturaComDrop(db, "Draken Spellweaver","Luminous Orb")
	CadastrarCriaturaComDrop(db, "Raging Mage","Luminous Orb")
	CadastrarCriaturaComDrop(db, "Warlock","Luminous Orb")
	CadastrarCriaturaComDrop(db, "Ancient Spawn of Morgathla","Luminous Orb")
	CadastrarCriaturaComDrop(db, "Lloy","Luminous Orb")
	CadastrarCriaturaComDrop(db, "Mad Mage","Luminous Orb")
	CadastrarCriaturaComDrop(db, "Ravenous Hunger","Luminous Orb")
	CadastrarCriaturaComDrop(db, "Reflection of a Mage","Luminous Orb")
	CadastrarCriaturaComDrop(db, "The Baron from Below","Luminous Orb")
	CadastrarCriaturaComDrop(db, "The Blazing Time Guardian","Luminous Orb")
	CadastrarCriaturaComDrop(db, "The Count of the Core","Luminous Orb")
	CadastrarCriaturaComDrop(db, "The Duke of the Depths","Luminous Orb")
	CadastrarCriaturaComDrop(db, "The Freezing Time Guardian","Luminous Orb")
	CadastrarCriaturaComDrop(db, "The Sandking","Luminous Orb")
	CadastrarCriaturaComDrop(db, "The Time Guardian","Luminous Orb")
	CadastrarCriaturaComDrop(db, "Brimstone Bug","Lump of Earth")
	CadastrarCriaturaComDrop(db, "Clay Guardian","Lump of Earth")
	CadastrarCriaturaComDrop(db, "Drillworm","Lump of Earth")
	CadastrarCriaturaComDrop(db, "Earth Elemental","Lump of Earth")
	CadastrarCriaturaComDrop(db, "Massive Earth Elemental","Lump of Earth")
	CadastrarCriaturaComDrop(db, "Muddy Earth Elemental","Lump of Earth")
	CadastrarCriaturaComDrop(db, "Earth Overlord","Lump of Earth")
	CadastrarCriaturaComDrop(db, "Sulphur Scuttler","Lump of Earth")
	CadastrarCriaturaComDrop(db, "The Shatterer","Lump of Earth")
	CadastrarCriaturaComDrop(db, "Mad Froth","Lost Thrower")
	CadastrarCriaturaComDrop(db, "Burning Gladiator","Magma Boots")
	CadastrarCriaturaComDrop(db, "Crazed Summer Vanguard","Magma Boots")
	CadastrarCriaturaComDrop(db, "Dragon Lord Hatchling","Magma Boots")
	CadastrarCriaturaComDrop(db, "Feral Sphinx","Magma Boots")
	CadastrarCriaturaComDrop(db, "Hellflayer","Magma Boots")
	CadastrarCriaturaComDrop(db, "Hellhound","Magma Boots")
	CadastrarCriaturaComDrop(db, "Honey Elemental","Magma Boots")
	CadastrarCriaturaComDrop(db, "Infernal Demon","Magma Boots")
	CadastrarCriaturaComDrop(db, "Infernalist","Magma Boots")
	CadastrarCriaturaComDrop(db, "Lava Golem","Magma Boots")
	CadastrarCriaturaComDrop(db, "Magma Crawler","Magma Boots")
	CadastrarCriaturaComDrop(db, "Manticore","Magma Boots")
	CadastrarCriaturaComDrop(db, "Massive Fire Elemental","Magma Boots")
	CadastrarCriaturaComDrop(db, "Orc Warlord","Magma Boots")
	CadastrarCriaturaComDrop(db, "Pirat Bombardier","Magma Boots")
	CadastrarCriaturaComDrop(db, "Sphinx","Magma Boots")
	CadastrarCriaturaComDrop(db, "Sulphider","Magma Boots")
	CadastrarCriaturaComDrop(db, "Wandering Pillar","Magma Boots")
	CadastrarCriaturaComDrop(db, "Bibby Bloodbath","Magma Boots")
	CadastrarCriaturaComDrop(db, "Count Vlarkorth","Magma Boots")
	CadastrarCriaturaComDrop(db, "Sister Hetai","Magma Boots")
	CadastrarCriaturaComDrop(db, "The Souldespoler","Magma Boots")
	CadastrarCriaturaComDrop(db, "Warlord Ruzad","Magma Boots")
	CadastrarCriaturaComDrop(db, "Lava Golem","Magma Clump")
	CadastrarCriaturaComDrop(db, "Magma Crawler","Magma Clump")
	CadastrarCriaturaComDrop(db, "Vulcongra","Magma Clump")
	CadastrarCriaturaComDrop(db, "Walking Pillar","Magma Clump")
	CadastrarCriaturaComDrop(db, "Wandering Pillar","Magma Clump")
	CadastrarCriaturaComDrop(db, "Weeper","Magma Clump")
	CadastrarCriaturaComDrop(db, "Afflicted Strider","Magma Coat")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	CadastrarCriaturaComDrop(db, "","")
	
}